const SALARY_RANGE = "SALARY_RANGE";
const FP_RANGE = "FP_RANGE";
const SALARY_CAP = "SALARY_CAP";
const PROJECTED_OWNERSHIP_CAP = "PROJECTED_OWNERSHIP_CAP";
const NUM_OF_LINEUPS = "NUM_OF_LINEUPS";
const FLEX_POSITIONS = "FLEX_POSITIONS";
const DISALLOW_PASSCATCHER = "DISALLOW_PASSCATCHER";
const FORCE_PLAYER = "FORCE_PLAYER";
const FORCE_ATLEAST = "FORCE_ATLEAST";
const PRIORITIZE = "PRIORITIZE";
const RANDOMIZATION = "RANDOMIZATION";
const PLAYER_EXPOSURE = "PLAYER_EXPOSURE";
const MODE = "MODE";
const PROJECTION_FPTs = "PROJECTION_FPTs";
const UNIQUE_PLAYER = "UNIQUE_PLAYER";
const PLAYER_VS_DEFENCE = "PLAYER_VS_DEFENCE";
const BROWSER_SERVER = "BROWSER_SERVER";
export {
  SALARY_CAP,
  SALARY_RANGE,
  FP_RANGE,
  PROJECTED_OWNERSHIP_CAP,
  NUM_OF_LINEUPS,
  FLEX_POSITIONS,
  DISALLOW_PASSCATCHER,
  FORCE_ATLEAST,
  FORCE_PLAYER,
  PRIORITIZE,
  RANDOMIZATION,
  PLAYER_EXPOSURE,
  MODE,
  PROJECTION_FPTs,
  UNIQUE_PLAYER,
  PLAYER_VS_DEFENCE,
  BROWSER_SERVER
};
