const LEGACY_ARRAY = 'LEGACY_ARRAY';
const PER_TEAM_ARRAY = 'PER_TEAM_ARRAY';
const COMBINATION_ARRAY = 'COMBINATION_ARRAY';

const DELETE_FROM_LEGACY_ARRAY = "DELETE_FROM_LEGACY_ARRAY";
const DELETE_FROM_PERTEAM_ARRAY = "DELETE_FROM_PERTEAM_ARRAY";
const DELETE_FROM_COMBINATION_ARRAY = "DELETE_FROM_COMBINATION_ARRAY";

const CLEAR_ALL_STACKING_ARRAY = "CLEAR_ALL_STACKING_ARRAY";

const CORRELATION_SECONDARY_ID = "CORRELATION_SECONDARY_ID";

export {LEGACY_ARRAY, PER_TEAM_ARRAY, COMBINATION_ARRAY, DELETE_FROM_PERTEAM_ARRAY, DELETE_FROM_LEGACY_ARRAY, DELETE_FROM_COMBINATION_ARRAY, CLEAR_ALL_STACKING_ARRAY, CORRELATION_SECONDARY_ID};