const SELECTED = "SELECTED";
const UNSELECTED = "UNSELECTED";
const SELECT_SLATE = "SELECT_SLATE";
const GAMES = "GAMES";
const CLEAR_SELECTED = "CLEAR_SELECTED";
const ICONS = "ICONS";
const SET_SLATE_PLAYERS = "SET_SLATE_PLAYERS";
const CLEAR_SLATE_PLAYERS = "CLEAR_SLATE_PLAYERS";

export {SELECTED, UNSELECTED, SELECT_SLATE, GAMES, CLEAR_SELECTED, ICONS, SET_SLATE_PLAYERS, CLEAR_SLATE_PLAYERS};