const CORRELATION = "CORRELATION";
const CORRELATION_ARRAY = "CORRELATION_ARRAY";
const LEGACY = "LEGACY";
const PER_TEAM = "PER_TEAM";
const COMBINATION = "COMBINATION";
const DELETE_LEGACY = "DELETE_LEGACY";
const DELETE_PER_TEAM = "DELETE_PER_TEAM";
const DELETE_COMBINATION = "DELETE_COMBINATION";
const DELETE_CORRELATION = "DELETE_CORRELATION";
const CLEAR_STACKING = "CLEAR_STACKING";
 
export {
    CORRELATION,
    LEGACY,
    PER_TEAM,
    COMBINATION,
    CORRELATION_ARRAY,
    DELETE_LEGACY,
    DELETE_PER_TEAM,
    DELETE_COMBINATION,
    DELETE_CORRELATION,
    CLEAR_STACKING
}