const CORRELATION = "CORRELATION";
const CORRELATION_ARRAY = "CORRELATION_ARRAY";
const LEGACY = "LEGACY";
const PER_TEAM = "PER_TEAM";
const COMBINATION = "COMBINATION";
const DELETE_LEGACY = "DELETE_LEGACY";
const DELETE_PER_TEAM = "DELETE_PER_TEAM";
const DELETE_COMBINATION = "DELETE_COMBINATION";
const DELETE_CORRELATION = "DELETE_CORRELATION";
const CLEAR_STACKING = "CLEAR_STACKING";
const STACKING_ARRAY_LEGACY = "STACKING_ARRAY_LEGACY";
const STACKING_ARRAY_PERTEAM = "STACKING_ARRAY_PERTEAM";
const STACKING_ARRAY_COMBINATION = "STACKING_ARRAY_COMBINATION";
const REMOVE_STACKING_ARRAY_LEGACY = "STACKING_ARRAY_LEGACY";
const REMOVE_STACKING_ARRAY_PERTEAM = "STACKING_ARRAY_PERTEAM";
const REMOVE_STACKING_ARRAY_COMBINATION = "STACKING_ARRAY_COMBINATION";
 
export {
    CORRELATION,
    LEGACY,
    PER_TEAM,
    COMBINATION,
    CORRELATION_ARRAY,
    DELETE_LEGACY,
    DELETE_PER_TEAM,
    DELETE_COMBINATION,
    DELETE_CORRELATION,
    CLEAR_STACKING,
    STACKING_ARRAY_COMBINATION,
    STACKING_ARRAY_PERTEAM,
    STACKING_ARRAY_LEGACY,
    REMOVE_STACKING_ARRAY_COMBINATION,
    REMOVE_STACKING_ARRAY_PERTEAM,
    REMOVE_STACKING_ARRAY_LEGACY
}