const IS_ALL = "IS_ALL";
const IS_NONE = "IS_NONE";
const IS_CHECKED = "IS_CHECKED";
const IS_UNCHECKED = "IS_UNCHECKED";
const IS_DELETE = "IS_DELETE";
const PLAYER_CHECKED = "PLAYER_CHECKED";
const PLAYER_UNCHECKED = "PLAYER_UNCHECKED";
const OPTIMIZE = "OPTIMIZE";
const FANTASY_POINTS = "FANTASY_POINTS";
const PROJECTION = "PROJECTION";
const FINAL_FPTS = "FINAL_FPTS";
const SALARY = "SALARY";
const TOTAL_POWNS = "TOTAL_POWNS";
const SET_LINEUPS = "SET_LINEUPS";
const SET_TOTAL_PLAYERS = "SET_TOTAL_PLAYERS";
const SET_IS_OPTIMIZED = "SET_IS_OPTIMIZED";
const CLEAR_EVERY_STATE = "CLEAR_EVERY_STATE";

export {
    IS_ALL,
    IS_NONE,
    IS_CHECKED,
    IS_UNCHECKED,
    IS_DELETE, 
    PLAYER_CHECKED,
    PLAYER_UNCHECKED,
    OPTIMIZE,
    FANTASY_POINTS,
    PROJECTION,
    FINAL_FPTS,
    SALARY,
    TOTAL_POWNS,
    SET_LINEUPS,
    SET_TOTAL_PLAYERS,
    SET_IS_OPTIMIZED,
    CLEAR_EVERY_STATE
}