const game = [
  {
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    teamSpread: 3.5,
    oppSpread: -3.5,
    date: "2021-01-04",
    time: "15:05:00",
    total: 53,
    bg: "#BADFAF"
  },
  {
    team: "https://cdn.dfsarmy.com/images/teams/nfl/buf.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/kc.svg",
    teamSpread: 3,
    oppSpread: -3,
    date: "2021-01-24",
    time: "18:40:00",
    total: 54.5,
    bg: "#BADFAF"
  },
  {
    team: "https://cdn.dfsarmy.com/images/teams/nfl/bal.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/ten.svg",
    teamSpread: 3.5,
    oppSpread: -3.5,
    date: "2021-01-24",
    time: "18:40:00",
    total: 53.5,
    bg: "#BADFAF"
  }
];

const playersData = [
  {
    id: 1,
    name: "Derrick Henry",
    pos: "RB",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/ten.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/bal.svg",
    dvp: 0,
    salary: 9200,
    dollarFpts: 2.4,
    projection: 22.06,
    finalFpts: 8.1,
    rating: 0,
    fpts: 22.06,
    projOwn: 31.01,
    isChecked: true,
    isLocked: false
  },
  {
    id: 2,
    name: "Alvin Kamara",
    pos: "RB",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/no.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/chi.svg",
    dvp: 6,
    salary: 8500,
    dollarFpts: 2.44,
    projection: 20.07,
    finalFpts: 19.6,
    rating: 0,
    fpts: 20.07,
    projOwn: 54.99,
    isChecked: true,
    isLocked: false
  },
  {
    id: 3,
    name: "Lamar Jackson",
    pos: "QB",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/bal.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/ten.svg",
    dvp: 19,
    salary: 7800,
    dollarFpts: 3.34,
    projection: 26.09,
    finalFpts: 28.76,
    rating: 0,
    fpts: 26.09,
    projOwn: 31.78,
    isChecked: true,
    isLocked: false
  },
  {
    id: 4,
    name: "Travis Kelce",
    pos: "TE",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/kc.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/chi.svg",
    dvp: 23,
    salary: 8000,
    dollarFpts: 2.9,
    projection: 23.18,
    finalFpts: 39.8,
    rating: 0,
    fpts: 23.18,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 5,
    name: "Mike Evans",
    pos: "WR",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 2,
    salary: 5800,
    dollarFpts: 2.57,
    projection: 14.92,
    finalFpts: 14.1,
    rating: 0,
    fpts: 14.92,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 6,
    name: "Leonard Fournette",
    pos: "RB",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 25,
    salary: 5300,
    dollarFpts: 2.93,
    projection: 15.54,
    finalFpts: 18.4,
    rating: 0,
    fpts: 15.54,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 7,
    name: "Tom Brady",
    pos: "QB",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 24,
    salary: 6100,
    dollarFpts: 3.28,
    projection: 20.02,
    finalFpts: 20.1,
    rating: 0,
    fpts: 20.02,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 8,
    name: "Tyreek Hill",
    pos: "WR",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 21,
    salary: 7200,
    dollarFpts: 3.08,
    projection: 22.19,
    finalFpts: 29.2,
    rating: 0,
    fpts: 22.19,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 9,
    name: "Chris Godwin",
    pos: "WR",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 2,
    salary: 5400,
    dollarFpts: 3.05,
    projection: 16.46,
    finalFpts: 19.6,
    rating: 0,
    fpts: 16.46,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 10,
    name: "Ronald Jones II",
    pos: "RB",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 25,
    salary: 4600,
    dollarFpts: 2.47,
    projection: 11.36,
    finalFpts: 1.6,
    rating: 0,
    fpts: 11.36,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 11,
    name: "Scotty Miller",
    pos: "WR",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 2,
    salary: 3400,
    dollarFpts: 0.52,
    projection: 1.76,
    finalFpts: 11.6,
    rating: 0,
    fpts: 1.76,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  },
  {
    id: 12,
    name: "Demarcus Robinson",
    pos: "WR",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/kc.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/buf.svg",
    dvp: 21,
    salary: 3700,
    dollarFpts: 0.44,
    projection: 1.63,
    finalFpts: 0,
    rating: 0,
    fpts: 1.63,
    projOwn: 0,
    isChecked: true,
    isLocked: false
  }
];

const excludedList = [
  {
    id: 10,
    name: "Ronald Jones II",
    pos: "RB",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 25,
    salary: 4600,
    dollarFpts: 2.47,
    projection: 11.36,
    finalFpts: 1.6,
    rating: 0,
    fpts: 11.36,
    projOwn: 0,
    isChecked: false,
    isLocked: false
  },
  {
    id: 11,
    name: "Scotty Miller",
    pos: "WR",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/tb.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/gb.svg",
    dvp: 2,
    salary: 3400,
    dollarFpts: 0.52,
    projection: 1.76,
    finalFpts: 11.6,
    rating: 0,
    fpts: 1.76,
    projOwn: 0,
    isChecked: false,
    isLocked: false
  },
  {
    id: 12,
    name: "Demarcus Robinson",
    pos: "WR",
    team: "https://cdn.dfsarmy.com/images/teams/nfl/kc.svg",
    opp: "https://cdn.dfsarmy.com/images/teams/nfl/buf.svg",
    dvp: 21,
    salary: 3700,
    dollarFpts: 0.44,
    projection: 1.63,
    finalFpts: 0,
    rating: 0,
    fpts: 1.63,
    projOwn: 0,
    isChecked: false,
    isLocked: false
  }
]

const lineup = [
  {
    name: "Laviska Shenault Jr.",
    Pos: "QB",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  },
  {
    name: "Laviska Shenault Jr.",
    Pos: "WR",
    team: "https://domination.dfsarmy.com/images/teams/nfl/jax.svg",
    Fpts: "13.27",
    exp: "67%(2)",
    projOwn: "6.66",
    min: "0%",
    max: "100%"
  }
];

const totalLineUps = [
  { Projection: 150, Salary: 50000, FPTs: 170, total: "200%" },
  { Projection: 149.23, Salary: 50000, FPTs: 170, total: "200%" },
  { Projection: 180.82, Salary: 50000, FPTs: 170, total: "200%" }
];

export { playersData, lineup, totalLineUps, game, excludedList };
