const CHAIN_PLAYER = "CHAIN_PLAYER";
const LOCK_PLAYER = "LOCK_PLAYER";
const UNLOCK_PLAYER = "UNLOCK_PLAYER";
const CHECKED = "CHECKED";
const UNCHECKED = "UNCHECKED";
const FPTS = "FPTS";
const ALL = "ALL";
const MY_PLAYER = "MY_PLAYER";
const EXCLUDED_PLAYER = "EXCLUDED_PLAYER";
const LOCKED_PLAYER = "LOCKED_PLAYER";
const CALCULATE_COST = "CALCULATE_COST";
const CLEAR_ALL = "CLEAR_ALL";
const TOTAL = "TOTAL";
const FINAL_TOTAL = "FINAL_TOTAL"
const EXPMIN = "EXPMIN";
const EXPMAX = "EXPMAX";
const SELECTALL = "SELECTALL";
const CLEARALLCHECK = "CLEARALLCHECK";
const CLEARALLPLAYER = "CLEARALLPLAYER";
const CLEARMYPLAYER = "CLEARMYPLAYER";
const FIRST_EXCLUSION = "FIRST_EXCLUSION";
const REMOVE_FROM_SELECTED_PLAYER = "REMOVE_FROM_SELECTED_PLAYER";

export {
  CHAIN_PLAYER,
  LOCK_PLAYER,
  CHECKED,
  UNCHECKED,
  FPTS,
  UNLOCK_PLAYER,
  ALL,
  MY_PLAYER,
  EXCLUDED_PLAYER,
  LOCKED_PLAYER,
  CALCULATE_COST,
  CLEAR_ALL,
  TOTAL,
  EXPMIN,
  EXPMAX,
  SELECTALL,
  CLEARALLCHECK,
  FINAL_TOTAL,
  CLEARALLPLAYER,
  CLEARMYPLAYER,
  FIRST_EXCLUSION
};
