const CHAIN_PLAYER = "CHAIN_PLAYER";
const LOCK_PLAYER = "LOCK_PLAYER";
const UNLOCK_PLAYER = "UNLOCK_PLAYER";
const CHECKED = "CHECKED";
const UNCHECKED = "UNCHECKED";
const FPTS = "FPTS";
const ALL = "ALL";
const MY_PLAYER = "MY_PLAYER";
const EXCLUDED_PLAYER = "EXCLUDED_PLAYER";
const LOCKED_PLAYER = "LOCKED_PLAYER";

export {
  CHAIN_PLAYER,
  LOCK_PLAYER,
  CHECKED,
  UNCHECKED,
  FPTS,
  UNLOCK_PLAYER,
  ALL,
  MY_PLAYER,
  EXCLUDED_PLAYER,
  LOCKED_PLAYER
};
